//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Postamat12
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Ключ.
    /// </summary>
    // *** Start programmer edit section *** (Ключ CustomAttributes)

    // *** End programmer edit section *** (Ключ CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КлючE", new string[] {
            "СгенКлюч as \'Сген ключ\'",
            "Пользователь as \'Пользователь\'",
            "Пользователь.ФИО as \'ФИО\'"}, Hidden=new string[] {
            "Пользователь.ФИО"})]
    [MasterViewDefineAttribute("КлючE", "Пользователь", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [View("КлючL", new string[] {
            "СгенКлюч as \'Сген ключ\'",
            "Пользователь.ФИО as \'ФИО\'"})]
    public class Ключ : ICSSoft.STORMNET.DataObject
    {
        
        private int fСгенКлюч;
        
        private IIS.Postamat12.Пользователь fПользователь;
        
        // *** Start programmer edit section *** (Ключ CustomMembers)

        // *** End programmer edit section *** (Ключ CustomMembers)

        
        /// <summary>
        /// СгенКлюч.
        /// </summary>
        // *** Start programmer edit section *** (Ключ.СгенКлюч CustomAttributes)

        // *** End programmer edit section *** (Ключ.СгенКлюч CustomAttributes)
        public virtual int СгенКлюч
        {
            get
            {
                // *** Start programmer edit section *** (Ключ.СгенКлюч Get start)

                // *** End programmer edit section *** (Ключ.СгенКлюч Get start)
                int result = this.fСгенКлюч;
                // *** Start programmer edit section *** (Ключ.СгенКлюч Get end)

                // *** End programmer edit section *** (Ключ.СгенКлюч Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Ключ.СгенКлюч Set start)

                // *** End programmer edit section *** (Ключ.СгенКлюч Set start)
                this.fСгенКлюч = value;
                // *** Start programmer edit section *** (Ключ.СгенКлюч Set end)

                // *** End programmer edit section *** (Ключ.СгенКлюч Set end)
            }
        }
        
        /// <summary>
        /// Ключ.
        /// </summary>
        // *** Start programmer edit section *** (Ключ.Пользователь CustomAttributes)

        // *** End programmer edit section *** (Ключ.Пользователь CustomAttributes)
        [PropertyStorage(new string[] {
                "Пользователь"})]
        [NotNull()]
        public virtual IIS.Postamat12.Пользователь Пользователь
        {
            get
            {
                // *** Start programmer edit section *** (Ключ.Пользователь Get start)

                // *** End programmer edit section *** (Ключ.Пользователь Get start)
                IIS.Postamat12.Пользователь result = this.fПользователь;
                // *** Start programmer edit section *** (Ключ.Пользователь Get end)

                // *** End programmer edit section *** (Ключ.Пользователь Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Ключ.Пользователь Set start)

                // *** End programmer edit section *** (Ключ.Пользователь Set start)
                this.fПользователь = value;
                // *** Start programmer edit section *** (Ключ.Пользователь Set end)

                // *** End programmer edit section *** (Ключ.Пользователь Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КлючE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлючE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлючE", typeof(IIS.Postamat12.Ключ));
                }
            }
            
            /// <summary>
            /// "КлючL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлючL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлючL", typeof(IIS.Postamat12.Ключ));
                }
            }
        }
    }
}
