//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Postamat12
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Посылка.
    /// </summary>
    // *** Start programmer edit section *** (Посылка CustomAttributes)

    // *** End programmer edit section *** (Посылка CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПосылкаE", new string[] {
            "Номер as \'Номер\'",
            "Статус as \'Статус\'",
            "Логистика as \'Логистика\'",
            "Логистика.Информация as \'Информация\'",
            "Логистика.Состояние as \'Состояние посылки\'",
            "Ключ as \'Сгенерированный ключ\'",
            "Ключ.СгенКлюч as \'Сгенерированный ключ\'",
            "Пользователь as \'ФИО пользователя\'",
            "Пользователь.ФИО as \'ФИО пользователя\'"}, Hidden=new string[] {
            "Логистика.Информация",
            "Ключ.СгенКлюч",
            "Пользователь.ФИО"})]
    [MasterViewDefineAttribute("ПосылкаE", "Логистика", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Информация")]
    [MasterViewDefineAttribute("ПосылкаE", "Ключ", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "СгенКлюч")]
    [MasterViewDefineAttribute("ПосылкаE", "Пользователь", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [View("ПосылкаL", new string[] {
            "Номер as \'Номер\'",
            "Статус as \'Статус\'",
            "Логистика.Информация as \'Информация посылки\'",
            "Логистика.Состояние as \'Состояние посылки\'",
            "Ключ.СгенКлюч as \'Сгенерированный ключ\'",
            "Пользователь.ФИО as \'ФИО пользователя\'"})]
    public class Посылка : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        private IIS.Postamat12.Статус fСтатус;
        
        private IIS.Postamat12.Логистика fЛогистика;
        
        private IIS.Postamat12.Ключ fКлюч;
        
        private IIS.Postamat12.Пользователь fПользователь;
        
        // *** Start programmer edit section *** (Посылка CustomMembers)

        // *** End programmer edit section *** (Посылка CustomMembers)

        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (Посылка.Номер CustomAttributes)

        // *** End programmer edit section *** (Посылка.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (Посылка.Номер Get start)

                // *** End programmer edit section *** (Посылка.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (Посылка.Номер Get end)

                // *** End programmer edit section *** (Посылка.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Посылка.Номер Set start)

                // *** End programmer edit section *** (Посылка.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (Посылка.Номер Set end)

                // *** End programmer edit section *** (Посылка.Номер Set end)
            }
        }
        
        /// <summary>
        /// Статус.
        /// </summary>
        // *** Start programmer edit section *** (Посылка.Статус CustomAttributes)

        // *** End programmer edit section *** (Посылка.Статус CustomAttributes)
        public virtual IIS.Postamat12.Статус Статус
        {
            get
            {
                // *** Start programmer edit section *** (Посылка.Статус Get start)

                // *** End programmer edit section *** (Посылка.Статус Get start)
                IIS.Postamat12.Статус result = this.fСтатус;
                // *** Start programmer edit section *** (Посылка.Статус Get end)

                // *** End programmer edit section *** (Посылка.Статус Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Посылка.Статус Set start)

                // *** End programmer edit section *** (Посылка.Статус Set start)
                this.fСтатус = value;
                // *** Start programmer edit section *** (Посылка.Статус Set end)

                // *** End programmer edit section *** (Посылка.Статус Set end)
            }
        }
        
        /// <summary>
        /// Посылка.
        /// </summary>
        // *** Start programmer edit section *** (Посылка.Ключ CustomAttributes)

        // *** End programmer edit section *** (Посылка.Ключ CustomAttributes)
        [PropertyStorage(new string[] {
                "Ключ"})]
        [NotNull()]
        public virtual IIS.Postamat12.Ключ Ключ
        {
            get
            {
                // *** Start programmer edit section *** (Посылка.Ключ Get start)

                // *** End programmer edit section *** (Посылка.Ключ Get start)
                IIS.Postamat12.Ключ result = this.fКлюч;
                // *** Start programmer edit section *** (Посылка.Ключ Get end)

                // *** End programmer edit section *** (Посылка.Ключ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Посылка.Ключ Set start)

                // *** End programmer edit section *** (Посылка.Ключ Set start)
                this.fКлюч = value;
                // *** Start programmer edit section *** (Посылка.Ключ Set end)

                // *** End programmer edit section *** (Посылка.Ключ Set end)
            }
        }
        
        /// <summary>
        /// Посылка.
        /// </summary>
        // *** Start programmer edit section *** (Посылка.Логистика CustomAttributes)

        // *** End programmer edit section *** (Посылка.Логистика CustomAttributes)
        [PropertyStorage(new string[] {
                "Логистика"})]
        [NotNull()]
        public virtual IIS.Postamat12.Логистика Логистика
        {
            get
            {
                // *** Start programmer edit section *** (Посылка.Логистика Get start)

                // *** End programmer edit section *** (Посылка.Логистика Get start)
                IIS.Postamat12.Логистика result = this.fЛогистика;
                // *** Start programmer edit section *** (Посылка.Логистика Get end)

                // *** End programmer edit section *** (Посылка.Логистика Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Посылка.Логистика Set start)

                // *** End programmer edit section *** (Посылка.Логистика Set start)
                this.fЛогистика = value;
                // *** Start programmer edit section *** (Посылка.Логистика Set end)

                // *** End programmer edit section *** (Посылка.Логистика Set end)
            }
        }
        
        /// <summary>
        /// Посылка.
        /// </summary>
        // *** Start programmer edit section *** (Посылка.Пользователь CustomAttributes)

        // *** End programmer edit section *** (Посылка.Пользователь CustomAttributes)
        [PropertyStorage(new string[] {
                "Пользователь"})]
        [NotNull()]
        public virtual IIS.Postamat12.Пользователь Пользователь
        {
            get
            {
                // *** Start programmer edit section *** (Посылка.Пользователь Get start)

                // *** End programmer edit section *** (Посылка.Пользователь Get start)
                IIS.Postamat12.Пользователь result = this.fПользователь;
                // *** Start programmer edit section *** (Посылка.Пользователь Get end)

                // *** End programmer edit section *** (Посылка.Пользователь Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Посылка.Пользователь Set start)

                // *** End programmer edit section *** (Посылка.Пользователь Set start)
                this.fПользователь = value;
                // *** Start programmer edit section *** (Посылка.Пользователь Set end)

                // *** End programmer edit section *** (Посылка.Пользователь Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПосылкаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПосылкаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПосылкаE", typeof(IIS.Postamat12.Посылка));
                }
            }
            
            /// <summary>
            /// "ПосылкаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПосылкаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПосылкаL", typeof(IIS.Postamat12.Посылка));
                }
            }
        }
    }
}
