//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Postamat12
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Регистр посылок.
    /// </summary>
    // *** Start programmer edit section *** (РегистрПосылок CustomAttributes)

    // *** End programmer edit section *** (РегистрПосылок CustomAttributes)
    [AutoAltered()]
    [Caption("Регистр посылок")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("РегистрПосылокE", new string[] {
            "Номер as \'Номер\'",
            "Посылка as \'Посылка\'",
            "Посылка.Номер as \'Номер\'"}, Hidden=new string[] {
            "Посылка.Номер"})]
    [MasterViewDefineAttribute("РегистрПосылокE", "Посылка", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Номер")]
    public class РегистрПосылок : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        private IIS.Postamat12.Посылка fПосылка;
        
        private IIS.Postamat12.Хранение fХранение;
        
        // *** Start programmer edit section *** (РегистрПосылок CustomMembers)

        // *** End programmer edit section *** (РегистрПосылок CustomMembers)

        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (РегистрПосылок.Номер CustomAttributes)

        // *** End programmer edit section *** (РегистрПосылок.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (РегистрПосылок.Номер Get start)

                // *** End programmer edit section *** (РегистрПосылок.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (РегистрПосылок.Номер Get end)

                // *** End programmer edit section *** (РегистрПосылок.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегистрПосылок.Номер Set start)

                // *** End programmer edit section *** (РегистрПосылок.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (РегистрПосылок.Номер Set end)

                // *** End programmer edit section *** (РегистрПосылок.Номер Set end)
            }
        }
        
        /// <summary>
        /// Регистр посылок.
        /// </summary>
        // *** Start programmer edit section *** (РегистрПосылок.Посылка CustomAttributes)

        // *** End programmer edit section *** (РегистрПосылок.Посылка CustomAttributes)
        [PropertyStorage(new string[] {
                "Посылка"})]
        [NotNull()]
        public virtual IIS.Postamat12.Посылка Посылка
        {
            get
            {
                // *** Start programmer edit section *** (РегистрПосылок.Посылка Get start)

                // *** End programmer edit section *** (РегистрПосылок.Посылка Get start)
                IIS.Postamat12.Посылка result = this.fПосылка;
                // *** Start programmer edit section *** (РегистрПосылок.Посылка Get end)

                // *** End programmer edit section *** (РегистрПосылок.Посылка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегистрПосылок.Посылка Set start)

                // *** End programmer edit section *** (РегистрПосылок.Посылка Set start)
                this.fПосылка = value;
                // *** Start programmer edit section *** (РегистрПосылок.Посылка Set end)

                // *** End programmer edit section *** (РегистрПосылок.Посылка Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Postamat12.Хранение.
        /// </summary>
        // *** Start programmer edit section *** (РегистрПосылок.Хранение CustomAttributes)

        // *** End programmer edit section *** (РегистрПосылок.Хранение CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Хранение"})]
        public virtual IIS.Postamat12.Хранение Хранение
        {
            get
            {
                // *** Start programmer edit section *** (РегистрПосылок.Хранение Get start)

                // *** End programmer edit section *** (РегистрПосылок.Хранение Get start)
                IIS.Postamat12.Хранение result = this.fХранение;
                // *** Start programmer edit section *** (РегистрПосылок.Хранение Get end)

                // *** End programmer edit section *** (РегистрПосылок.Хранение Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегистрПосылок.Хранение Set start)

                // *** End programmer edit section *** (РегистрПосылок.Хранение Set start)
                this.fХранение = value;
                // *** Start programmer edit section *** (РегистрПосылок.Хранение Set end)

                // *** End programmer edit section *** (РегистрПосылок.Хранение Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "РегистрПосылокE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РегистрПосылокE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РегистрПосылокE", typeof(IIS.Postamat12.РегистрПосылок));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of РегистрПосылок.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfРегистрПосылок CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfРегистрПосылок CustomAttributes)
    public class DetailArrayOfРегистрПосылок : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Postamat12.DetailArrayOfРегистрПосылок members)

        // *** End programmer edit section *** (IIS.Postamat12.DetailArrayOfРегистрПосылок members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type РегистрПосылок by index.
        /// </summary>
        /// <summary>
        /// Adds object with type РегистрПосылок.
        /// </summary>
        public DetailArrayOfРегистрПосылок(IIS.Postamat12.Хранение fХранение) : 
                base(typeof(РегистрПосылок), ((ICSSoft.STORMNET.DataObject)(fХранение)))
        {
        }
        
        public IIS.Postamat12.РегистрПосылок this[int index]
        {
            get
            {
                return ((IIS.Postamat12.РегистрПосылок)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Postamat12.РегистрПосылок dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
